// Spielzustand
const gameState = {
    money: 1000,
    energy: 0,
    energyCapacity: 0,
    energyProduction: 0,
    energyConsumption: 0,
    income: 0,
    passiveIncome: 0,
    day: 1,
    items: [],
    currentHour: 0,
    currentMinute: 0,
    dayPhase: 'night',
    dayStartTime: Date.now(),
    dayDuration: 2 * 60 * 1000,
    timers: [],
    selectedItem: null,
    passiveIncomeTimer: null,
    buildMode: null,
    tempItem: null,
    isDragging: false,
    draggedItem: null,
    dragOffsetX: 0,
    dragOffsetY: 0,
    lastEnergyUpdate: Date.now(),
    wheatStock: 0,
    autoPurchaseActive: false,
    totalProfit: 0,
    totalEnergy: 0,
    energyPrice: 1.00,
    wheatPrice: 0.50,
    weather: 'sunny',
    firstLoad: true,
    achievements: [],
    season: 'spring',
    loan: { amount: 0, interestRate: 0.05, repaymentDay: null },
    maintenanceDue: false
};
